name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build_project
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: ls
      
  test:
    name: run_tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: step1
        run: ls
